### ISSUE TITLE
[rush] `rush install` fails with npm@5

### ISSUE THREAD

**Issue by ryym** [Microsoft/web-build-tools#394] opened 2017-10-13 07:10 UTC
Hi,

Does not Rush support npm@5 yet?
Using npm@5, `rush install` results in the error when `common/temp` directory does not exist.

```
ERROR: Failed to parse package.json for foo: Invalid version: "file:projects/foo.tgz"
```

(The same error as https://github.com/Microsoft/web-build-tools/issues/354)

This becomes a problem when I run `rush install` for a cloned repository.
Usually `common/temp` does not be committed so `rush install` for a cloned repository always fail.

Reproduction steps:

1. set up package directories and `rush.json`
1. run `rush generate`
     - (`rush install` succeeds at this time)
1. remove `common/temp`
1. run `rush install`
    - `ERROR: Failed to parse package.json for ...`

I confirmed this error does not occur with npm@4.5.0.

environment:

- rush: 3.0.19
- npm: 5.3.0
- node: 6.9.5
- OS: macOS Sierra 10.12.6

**Comment by mtfranchetto** [comment] 2017-10-25 09:10
Got the same error today.

**Comment by HipsterZipster** [comment] 2017-10-27 00:12
@nickpape-msft  This issue was raised 2 weeks ago and earlier in #354, can you please lend us a hand? Considering we have a scripted workaround, I'm happy to contribute the code change back to Rush if you could just point me in the right direction.

On Node 8.7.0 with NPM 5.4.2 (and all other versions of npm 5.x that we've used), the problem has been deterministic and repeatable for every member of my team. This was a total blocker for us so I figured out a hacky solution that lets us move forward. 
@mtfranchetto @ryym try this out and let me know.

Before committing the `[root]/common/config/rush/npm-shrinkwrap.json`, run a node.js script (or just do a regex replace in your friendly text-editor) that changes:
- `/file:projects\/([\w\-]+)+.tgz/` (flags: `img`) 
to
- `file:projects\\\\$1`

Can someone from the Rush team pls point me to where this code change should go in the underlying Rush lib?

**Comment by mtfranchetto** [comment] 2017-10-27 12:04
@HipsterZipster Yes, it's working!

**Comment by ryym** [comment] 2017-10-27 13:18
@HipsterZipster I confirmed too. It works!

**Comment by pgonzal** [comment] 2017-10-27 18:03
Hey guys, sorry about the slow response.  I will investigate this morning.

FYI we tried upgrading to NPM 5 several times for our internal repos, but each time we had to rollback because of regressions in the NPM tool.  We got really frustrated by this and have been experimenting with migrating to [PNPM](https://github.com/pnpm/pnpm) instead of NPM.  It is a drop-in replacement that introduces a fundamentally different **node_modules** directory structure that makes the Rush symlinking algorithm much simpler, and should make installs a lot faster.  The PR is [here](https://github.com/Microsoft/web-build-tools/pull/383) if you're interested.  (We also looked at Yarn, but it's the same old crazy design as NPM, just with a much more solid implementation.)

Anyway if NPM 5 finally has a usable release, we should make sure it works.

**Comment by pgonzal** [comment] 2017-10-27 22:48
Update:  This seems to be a bug in [read-package-tree](https://www.npmjs.com/package/read-package-tree) which is how "rush link" scans the *node_modules* folder.  That library is part of NPM itself, but even when I upgrade to the version used by NPM 5, it still cannot read a folder containing tgz references.  (Even though "npm install" and "npm shrinkwrap" are totally cool with these references.)

It seems to be due to some difference in the package.json files emitted by NPM.  I'm trying to pin down what has changed exactly.  But I suspect the fix will be in **read-package-tree** not Rush.

**Comment by pgonzal** [comment] 2017-10-27 23:03
Actually it's looking like this is yet another NPM 5 regression:

Rush generates a **common/temp/package.json** that does this:
```json
  "dependencies": {
    "yargs": "~4.6.0",
    "z-schema": "~3.18.3",
    "@rush-temp/api-documenter": "file:./projects/api-documenter.tgz",
```

...and then our **common/temp/projects/api-documenter.tgz** contains a package.json like this:
```json
{
  "name": "@rush-temp/api-documenter",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
```

...but then NPM 5 installs a **common/temp/node_modules/@rush-temp/api-documenter/package.json** that wrongly has this:
```json
  "version": "file:projects/api-documenter.tgz"
```

...whereas under NPM 4 it looked like this:
```json
  "version": "0.0.0"
```

Could you open an issue or PR for the NPM tool?  I have so little interest in debugging NPM 5 any more at this point...  By hook or crook (i.e. PNPM or Yarn), we will ditch NPM by the end of this year.

**Comment by pgonzal** [comment] 2017-10-27 23:07
@nickpape @qz2017 @iclanton FYI

**Comment by nickpape-msft** [comment] 2017-10-28 00:12
@pgonzal FYI I am @nickpape-msft for work. @nickpape is my personal github.

**Comment by pgonzal** [comment] 2017-10-28 02:26
I started a conversation with NPM to see if they can fix this.

**Comment by HipsterZipster** [comment] 2017-10-29 03:38
Thank you @pgonzal for your attention to this and for uncovering the underlying issue within NPM. 
Did you create an issue with NPM? If so, can you provide link?

I assume this regression from the Rush perspective is an effect of the new `file:` symlink 'feature' (https://github.com/npm/npm/pull/15900) in which case rush may need to run an after generate task like my regex replace above in order to support it. Wdyt?

I agree it'd be amazing if NPM5 upped its game and removed the regressions, especially for big firms that block Yarn registry and invest in their own npm registries and license filtering solutions.
pnpm looks like an amazing option. I'd be excited to test out Rush support with it on my projects whenever you think it's or close to ready ;) 

I'd be interested in seeing how you get around their lack of support for shrinkwraps https://github.com/pnpm/pnpm#limitations

**Comment by pgonzal** [comment] 2017-10-30 18:30
I was able to isolate a simple repro.  I've opened [NPM issue 19006](https://github.com/npm/npm/issues/19006).

In the meantime we'll see if we can come up with a better workaround.

@nickpape-msft FYI

**Comment by pgonzal** [comment] 2017-11-04 02:23
Rush 4 has been [published](https://github.com/Microsoft/web-build-tools/wiki#november-3-2017---rush-4-released).  :-)

**Closed by pgonzal** 2017-11-04 02:23 UTC

**Comment by ryym** [comment] 2017-11-04 03:13
@pgonzal Thank you!
