### ISSUE TITLE
 Interface 'Gulp' incorrectly extends interface 'Orchestrator'.

### ISSUE THREAD

**Issue by wweiss** [Microsoft/web-build-tools#1197] opened 2019-03-29 23:13 UTC
When compiling a custom task for the gulp-core-build I continually encounter the following error:

```
Error - [tsc] ../../node_modules/@types/gulp/index.d.ts(15,15): error TS2430: Interface 'Gulp' incorrectly extends interface 'Orchestrator'.
Error - [tsc] node_modules/@microsoft/gulp-core-build/lib/GulpProxy.d.ts(6,22): error TS2420: Class 'GulpProxy' incorrectly implements interface 'Gulp'.
Error - 'tsc' sub task errored after 4.25 s 
 exited with code 2
```

The project can be seen here:
https://github.com/CodificationOrg/cutwater/tree/master/packages/cutwater-build-core

To reproduce:
- Clone the repo
- Run `yarn bootstrap` at the repo root
- Run `yarn build` at the repo root or in the `./packages/cutwater-build-core` directory

**Comment by octogonz** [comment] 2019-03-29 23:32
When I run `rush scan` in the project folder, I see this output:

```
  @codification/cutwater-core
  @codification/cutwater-logging
  @codification/cutwater-node-core
  @microsoft/node-library-build
  aws-lambda
  aws-sdk
  gulp
  middy
  mime
  rxjs
```

But the **package.json** lists only these dependencies:
```
  "dependencies": {
    "@microsoft/api-documenter": "^7.0.24",
    "@microsoft/gulp-core-build": "^3.9.23"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.2": "^0.2.19"
  },
```

This means you've got a bunch of [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/), which means the installation state may be inconsistent.  Please fix that first, then we'll take a look.  ;-)

**Comment by wweiss** [comment] 2019-03-29 23:45
Interesting, this is what I get:

```
Rush Multi-Project Build Tool 5.5.4 (unmanaged) - https://rushjs.io

Starting "rush scan"

Detected dependencies:
  @microsoft/api-documenter
  @microsoft/gulp-core-build
  @microsoft/node-library-build
  gulp
```

You are running `rush scan` in the `./packages/cutwater-build-core` directory?

**Comment by octogonz** [comment] 2019-03-29 23:51
Ooops, you're right.  I must have run it in the wrong folder heheh.  Lemme take one more look...

**Comment by octogonz** [comment] 2019-03-30 00:09
The error appears in this file:

**cutwater\\node_modules\\@microsoft\\gulp-core-build\\lib\\GulpProxy.d.ts**
```
export declare class GulpProxy extends Orchestrator implements gulp.Gulp {
    src: gulp.SrcMethod;
    dest: gulp.DestMethod;
    watch: gulp.WatchMethod;
    constructor(gulpInstance: gulp.Gulp);
    task(): any;
}
```

whose **package.json** says:
```js
{
  "name": "@microsoft/gulp-core-build",
  "version": "3.9.23",
  "dependencies": {
    . . .
    "@types/orchestrator": "0.0.30",
```


And if I press F12 on `extends Orchestrator` in the above code, I can see that it is coming from this file, which is  version `"0.0.30"` as expected:

**cutwater\\node_modules\\@types\\orchestrator\\index.d.ts**

If I press F12 on `implements gulp.Gulp` in the above code, it takes me here:

**cutwater\\node_modules\\@types\\gulp\\index.d.ts**
```js
. . .
import Orchestrator = require("orchestrator");
import VinylFile = require("vinyl");

declare namespace gulp {
    interface Gulp extends Orchestrator {
. . .
```

...and then if I press F12 on this `Orchestrator`, it takes me to this file, which is version `0.3.2` which is not what **gulp-core-build** was asking for:

**cutwater\\node_modules\\@types\\gulp\\node_modules\\@types\\orchestrator\\index.d.ts**
```js
{
    "name": "@types/orchestrator",
    "version": "0.3.2",
    "description": "TypeScript definitions for Orchestrator",
    . . .
```

I think this is the issue where alternate package managers don't handle `@types` versions the way NPM does.  There was a megathread for PNPM where this ended up getting fixed, see here  
 https://github.com/pnpm/pnpm/issues/1187#issuecomment-476012643

There was also a megathread for Yarn where they wanted DefinitelyTyped to redesign the way `@types` works.  They said they won't fix Yarn, but might accept a PR if someone in the community wanted to do the work.  Until then, your workaround would be to use Yarn `resolutions` to manually force the right version to get installed.  (If I'm understanding your issue correctly.)

**Comment by octogonz** [comment] 2019-03-30 00:17
(BTW I'd also point out that **cutwater\\node_modules** is a phantom **node_modules** folder, but if I remember right Yarn has to do that because its installation strategy doesn't support symlinks.)

**Comment by wweiss** [comment] 2019-03-30 14:58
Thank you so much - I've been fighting with this for over a day...

For future reference, adding this to the root **package.json** solved it:
```
  "resolutions": {
    "**/@types/orchestrator": "0.0.30"
  }
```

I think a big part of the problem is the following from the **package.json** inside of **@types/gulp**:
```
 "dependencies": {
        "@types/orchestrator": "*",
        "@types/vinyl": "*",
        "@types/node": "*"
    },
```
Clearly, it needs to specify a specific version or version range for orchestrator for things to work properly.  But, that's not a gulp-core-build problem :)

Regarding the phantom dependencies, yes, I believe that is how yarn workspaces handles shared packages.

**Closed** 2019-03-30 14:59 UTC
Labels: external issue

**Comment by octogonz** [comment] 2019-03-30 17:25
The DefinitelyTyped `@types` packages do not follow SemVer (by design), so the range has to be either `*` or an exact version. DefinitelyTyped uses a `*` everywhere, basically leaving the version selection up to consumers. The recent consensus was that this design is reasonable, except that the `*` should probably be a peer dependency, not a regular dependency. Some people are experimenting with this idea, and if it works, we'll open an issue asking them to make this design change.

**Comment by wweiss** [comment] 2019-03-30 17:46
Thanks, you learn something new every day!
