### ISSUE TITLE
[rush] A way to tell rush *not* to share certain modules?

### ISSUE THREAD

**Issue by Sushisource** [Microsoft/web-build-tools#987] opened 2018-12-11 22:12 UTC
Hi there,

Loving rush. Great tool. Ran into something today that I think may be a fairly common issue. I have two modules (a client and server) that both need the https://www.npmjs.com/package/secp256k1 library. The client is an electron app, and the server is a node app.

Since rush has them both symlinked to one instance of the secp256k1 lib, when it compiles, it links against the version of V8 that local Node is using, which makes sense. The problem is when you then go to run the electron app, it fails because of binary compatibility issues:

```
secp256k1.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
```

I can run `electron-rebuild` to fix this, but then the non-electron app won't work for the same reason.

Seemingly, if I just had a way to tell rush that I didn't want a certain module to be shared, but rather each module (or maybe just some that I specify) should have their own copy of it, then this problem would be fixed because electron-rebuild would only operate on the client's copy of secp256k1

I have a fairly urgent need to fix this, so if this seem like something reasonable I may be able to contribute it

**Comment by Sushisource** [comment] 2018-12-11 22:35
@pgonzal Thanks for the quick reply. I don't think the cyclic setting will fix things since the aforementioned `secp256k` lib isn't mine and isn't local.

The client and server modules that are mine, and are local, each need an independent copy (not symlinked to rush's common folder) of `secp256k1` in their `node_modules` dir so that they can be compiled against different V8 ABIs.

My proposal would be some configuration setting a-la:

```
independentCopies {
    client: ['secp256k1']
}
```

Where `client` is the name of my client module in this case. Here, yarn/npm install would be run twice, once for the common copy of secp256k1 that is symlinked into all modules except client, and once specially for client.

Is that making sense?

**Comment by pgonzal** [comment] 2018-12-12 00:34
Hmmm...  looks like the **secp256k1** project is shipping the **node-gyp** inputs.  By design, **node-gyp** projects are supposed to ship prebuilt binaries for each supported platform, and the Python / C++ compiler rig is only supposed to be required for people who work on the library project itself. It seems like this library is not following the best practices.

Do you need to publish an NPM package that depends on secp256k1?  If not, I would recommend to set up a custom build step that somehow eliminates writing outputs into the node_modules folder.

For example, if you have two V8 flavors A and B, you could create your own projects **secp256k1-v8a** and **secp256k1-v8b** that produces **secp256k1** binaries as part of their build step.  If they are shared internally at your company, you could publish these two packages to your private NPM feed.  Something like that...

**Comment by pgonzal** [comment] 2018-12-12 00:35
From [package.json](https://github.com/cryptocoinjs/secp256k1-node/blob/master/package.json#L42):
```
  "scripts": {
    "coverage": "RANDOM_TESTS_REPEAT=1 nyc tape test/index.js",
    "coverage-lcov": "npm run coverage && nyc report -r lcov",
    "install": "npm run rebuild || echo \"Secp256k1 bindings compilation fail. Pure JS implementation will be used.\"",
    "lint": "standard",
    "rebuild": "node-gyp rebuild",
    "test": "npm run lint && npm run unit",
    "test:browser": "karma start karma.conf.js",
    "unit": "tape test/index.js"
  },
```

That `"install"` hook is seriously incompatible with the NPM packaging model.  It is going to cause a lot of headaches.

**Comment by Sushisource** [comment] 2018-12-12 01:01
@pgonzal That's super helpful. Thanks for the info. I think we'll try to go for the build-our-own-copies solution, or perhaps see if we can find a better implementation.

Feel free to close this issue if there's nothing relevant to rush left.

**Comment by pgonzal** [comment] 2018-12-12 01:13
I'll close this issue for now, since there isn't clearly Rush-specific feature that would help with this problem.  You can reopen it if you run into trouble/questions with this approach.  Thanks!

**Closed by pgonzal** 2018-12-12 01:13 UTC
Labels: needs more info
