### ISSUE TITLE
[rush] VSCode node_modules folder is locked after rush package interactions

### ISSUE THREAD

**Issue by benjamind** [microsoft/web-build-tools#1172] opened 2019-03-21 22:03 UTC
This may not specifically be a Rush bug, although it is a very easy way to demonstrate the issue.

Under Windows when using VSCode with Rush to add packages or other similar operations that cause `node_modules` folder to be purged/relinked the following error will occur quite often:

```bash
ERROR: Error: Error: EPERM: operation not permitted, mkdir 'C:\XXXXX\node_modules'
Often this is caused by a file lock from a process such as your text editor, command prompt, or "gulp serve"
```
This appears to be due to TSServer within VSCode holding a reference to the node_modules folder. I believe this may be due to a directory watch that is being done to find new type definitions, but have not confirmed this yet.

[Link to gitter discussion](https://gitter.im/web-build-tools/web-build-tools?at=5c7eeefdbf7990126e5614fc)

Possible related VSCode issues:
https://github.com/Microsoft/vscode/issues/68576#issuecomment-463865605
https://github.com/Microsoft/TypeScript/issues/29407

**Comment by octogonz** [comment] 2019-03-21 22:04
@ScottHysom said:
> I noticed this started happening on my machines with VS Code's January 2019 (1.31.1) update.

**Comment by octogonz** [comment] 2019-04-22 22:21
The upstream issue https://github.com/Microsoft/TypeScript/issues/29407 still is not resolved.

For anyone who's hitting this, there is a workaround that avoids having to close all your VS Code windows:

> **Workaround:** Run this command to release the lock on the file:
> 
> <img alt="Screen Shot 2019-04-12 at 9 15 24 AM" width="245" src="https://user-images.githubusercontent.com/2193314/56051455-850cbb80-5d03-11e9-969d-67dcb4b46176.png">

**Comment by bsiegel** [comment] 2019-05-02 21:09
It appears the root cause was discovered to be this electron bug: https://github.com/electron/node/pull/97 and is fixed in VSCode Insiders and will be fixed in the next stable version of VSCode.

**Comment by octogonz** [comment] 2019-05-02 23:52
This is great.  Maybe we should keep this issue open until the VSCode update is released, in case others encounter the problem.

**Comment by poelstra** [comment] 2019-05-22 11:21
It's released! And apparently, it works, too! 🎉

**Comment by octogonz** [comment] 2019-05-22 13:58
Hurray!

**Closed by octogonz** 2019-05-22 13:58 UTC
Labels: external issue
