### ISSUE TITLE
[api-extractor] current version is unusable

### ISSUE THREAD

**Issue by ibezkrovnyi** [Microsoft/web-build-tools#736] opened 2018-07-05 20:57 UTC
@microsoft/api-extractor@5.9.1

## source
https://github.com/ibezkrovnyi/image-quantization/blob/master/src/image-q.ts

## [d.ts](https://unpkg.com/image-q@2.1.2/dist/esm/image-q.d.ts)
```ts
import * as constants from './constants';
import * as conversion from './conversion';
import * as distance from './distance';
import * as palette from './palette';
import * as image from './image';
import * as quality from './quality';
import * as utils from './utils';
export { 
  buildPalette, 
  buildPaletteSync, 
  applyPalette, 
  applyPaletteSync, 
  ImageQuantization, 
  PaletteQuantization, 
  ColorDistanceFormula 
} from './basicAPI';

export { 
  constants, 
  conversion, 
  distance, 
  palette, 
  image, 
  quality, 
  utils
};
```

## image-q.api.json
```ts
{
  "kind": "package",
  "name": "image-q",
  "summary": [],
  "remarks": [],
  "exports": {
    "applyPalette": {...},
    "applyPaletteSync": {...},
    "buildPalette": {...},
    "buildPaletteSync": {...}
  }
}
```

## actual result
only 4 top-level functions extracted

## expected to be extracted
* all functions
* interfaces
* type aliases
* primitives
* objects
* arrays
* classes
* es6namespace in statements like `import * as es6namespace from`

**Comment by pgonzal** [comment] 2018-07-06 12:57
Thanks for providing this repro. I am on vacation for the next couple weeks, but I can take a look when I get back. I suspect it is a configuration issue.

**Comment by pgonzal** [comment] 2018-11-22 07:32
The problematic syntax is:

```ts
import * as constants from './constants';
export { constants };
```

Closing, since this is a duplicate of issue https://github.com/Microsoft/web-build-tools/issues/663 which has more investigation.

**Closed by pgonzal** 2018-11-22 07:32 UTC
