### ISSUE TITLE
rush: unexpected versions of transitive @types/* dependencies are installed

### ISSUE THREAD

**Issue by elliottsj** [Microsoft/web-build-tools#750] opened 2018-07-17 00:35 UTC
Cross-posting the PR/issue from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27350

Example here: https://github.com/elliottsj/rush-pnpm-types-test

More details available in the PR. I think this is more of an issue with how DefinitelyTyped typings packages are versioned/published, but posting here in case this is something rush can fix.

**Comment by nickpape-msft** [comment] 2018-07-20 20:39
I'm not sure I understand the issue fully. It looks like [foo](https://github.com/elliottsj/rush-pnpm-types-test/blob/master/packages/foo-webpack-plugin/package.json) depends on both `tapable@^0` and `@types/webpack@^3`? Whereas [bar](https://github.com/elliottsj/rush-pnpm-types-test/blob/master/packages/bar-webpack-plugin/package.json) only depends on `webpack@^4`.

_[As a general note, you should try to run 'rush check' in your repo and generally avoid using different versions of dependencies.]

Rush does a thing called [implicitly pinned versions](https://rushjs.io/pages/advanced/pinned_versions/) where it will hoist anything that has a common version specifier to the root of the DAG. In this case, it would hoist `tapable@^0` to the root. When it installs webpack types later, their * makes both of them resolve correctly to `tapable@^0`.

Do you want `bar` to get the latest `tapable` types? If so, the easiest way to achieve this is to add something like `@types/tapable@^1` to `bar`'s package.json

**Comment by elliottsj** [comment] 2018-07-20 20:57
Ah nice, that pinned versions article helps a lot to understand the issue. Yes, it does appear that `tapable@^0` is hoisted to the root since it satisfies `@types/webpack@^4`'s semver constraints.

I have tried adding `"@types/tapable": "^1"` to bar's package.json, but unfortunately the same behaviour exists even after making that change. You can repro with: 

```shell
git clone https://github.com/elliottsj/rush-pnpm-types-test && cd rush-pnpm-types-test
rush install
cd packages/bar-webpack-plugin/
npm test
```

**Comment by nickpape-msft** [comment] 2018-07-20 21:01
FYI we introduced a `rushx` command that operates similar to `npm run`, although will eventually be getting strict command line enforcement. Just a heads up so you can avoid running `npm run` or `gulp` in future.

**Comment by nickpape-msft** [comment] 2018-07-20 23:01
Okay, I've done a bit of investigation. Rush appears to be acting correctly, but even with the workaround we tried it didn't work, so I think this is a PNPM issue.

The shrinkwrap has the correctly resolved versions for the top-level tarballs:

```yaml
  'file:projects/bar-webpack-plugin.tgz':
    dependencies:
      '@types/tapable': 1.0.4
      '@types/webpack': 4.4.7
      typescript: 2.9.2
      webpack: /webpack/4.16.1/webpack@4.16.1
    dev: false
    name: '@rush-temp/bar-webpack-plugin'
    resolution:
      integrity: sha512-t8I/thrQcyYOabLPMfEevg2ZQbUqIctcpqORx2D8cVIdSbhsuWi9dvziOGOBSXu1JK1wiB0O851pgPZMymb3qQ==
      tarball: 'file:projects/bar-webpack-plugin.tgz'
    version: 0.0.0
  'file:projects/foo-webpack-plugin.tgz':
    dependencies:
      '@types/tapable': 0.2.5
      '@types/webpack': 3.8.14
      typescript: 2.9.2
      webpack: /webpack/3.12.0/webpack@3.12.0
    dev: false
    name: '@rush-temp/foo-webpack-plugin'
    resolution:
      integrity: sha512-RctBHnFup8Bu84g8zKucZUoZ5UV/0OGLrgB0NQNm7cbPhUuysRCaQ46MwYEYURsAp8U4iINdnUDPOaT6lOTSvw==
      tarball: 'file:projects/foo-webpack-plugin.tgz'
    version: 0.0.0
```

Based on that, `bar-webpack-plugin` is getting `@types/tapable@1.0.4`, however if you look at the shrinkwrap for `@types/webpack`:

```yaml
/@types/webpack/3.8.14:
    dependencies:
      '@types/node': 10.5.2
      '@types/tapable': 0.2.5
      '@types/uglify-js': 3.0.3
      source-map: 0.6.1
    dev: false
    resolution:
      integrity: sha512-QljpyEEOgvFeF76Pi271NS/cVB7P0lrMp1b07b6cpii8d5BvN3qoN7TybL9MLdKRro1qyV9TxQqahuZDjAZrhg==
  /@types/webpack/4.4.7:
    dependencies:
      '@types/node': 10.5.2
      '@types/tapable': 0.2.5
      '@types/uglify-js': 3.0.3
      source-map: 0.6.1
    dev: false
    resolution:
      integrity: sha512-nwjQSPaVdEyM60ZfE/+SadTEgsuP7uXfHZ2n7c/a+G5f7K7esdlCu4f+po4DPfjJN7LeDC0e7kr4uOzLg5VOGw==
```

**What!?** Even though `bar-webpack-plugin` is providing `1.0.4`, `@types/webpack` is still getting `0.2.5`.

I think this may be related to the [PNPM React 15/16 deduping issue](https://github.com/pnpm/pnpm/issues/1187). Although what is odd is that `@types/tapable` isn't hoisted.

```yaml
dependencies:
  '@rush-temp/bar-webpack-plugin': 'file:projects/bar-webpack-plugin.tgz'
  '@rush-temp/foo-webpack-plugin': 'file:projects/foo-webpack-plugin.tgz'
  typescript: 2.9.2
```

**Comment by nickpape-msft** [comment] 2018-07-20 23:11
You can work around this issue with a `pnpmfile.js`. Here is an example:

```javascript
"use strict";

/**
 * This file defined custom hooks for pnpm
 * It is designed to be used to fixup "bad packages"
 * which require() things that are not in their package.json
 * This file is copied to the /common/temp folder during
 * "rush install" and "rush generate".
 *
 * You should run `rush update -p` or `rush update --full` after this
 *
 * You can read more about this file here:
 * https://github.com/pnpm/pnpm#hooks
 * https://github.com/pnpm/pnpm/issues/949
 *
 * Also, pnpm is considering moving this file to a better format,
 * such as a JSON configuration, rather than letting people
 * write their own custom hooks.
 *
 * DO NOT MODIFY THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
 */
module.exports = {
  hooks: {
    readPackage
  }
};

/**
 * This is the hook that is called after downloading a package.json
 * The variable `pkg` is a package.json object
 * We are expected to return the object.
 */
function readPackage(pkg) {
  if (pkg.name === '@types/webpack' && pkg.version.startsWith('4.')) {
    pkg.dependencies['@types/tapable'] = '^1';
  }
  return pkg;
}
```

I tested this in your repo and it seems to work. Make sure to run `rush update --full` afterwards.

[Although if you don't mind, please leave the repro branch alone. I want to be able to let Zoltan take a look at it.]

**Comment by elliottsj** [comment] 2018-07-23 17:48
Thanks, that helps a lot!

The thing that's still not clear to me though is whether DefinitelyTyped is doing the right thing here by using `*` semver constraints for @types dependencies. Relying on the parent package (bar-webpack-plugin) to provide the "correct" version of @types/tapable feels more like a workaround.

**Comment by pgonzal** [comment] 2018-07-23 19:31
> The thing that's still not clear to me though is whether DefinitelyTyped is doing the right thing here by using `*` semver constraints for @types dependencies. Relying on the parent package (bar-webpack-plugin) to provide the "correct" version of @types/tapable feels more like a workaround.

I felt the same way. However when I chatted with the TypeScript compiler owners about this, they eventually convinced me that it's the only reasonable design (as things stand today).

The problem is that -- by design-- the `@types` packages never follow SemVer:  Their version numbers are meant to more-or-less correspond to the underlying JavaScript library version, and they frequently have "breaking changes" that involve the type system (even though there may be no actual signature change for the underlying library API).

Thus, the only reasonable alternative to `"*"` would be a specific locked version number (without any range or SemVer caret `"^1.2.3"`).  But if you have many typing packages with interdependencies, locked versions would cause them to be at best a set of packages whose versions are all locked together, or at worst (due to diamond dependencies) a problem of side-by-side versions that are impossible for the application to resolve.

Another issue is ambient typings (e.g. `@types/node`) which describe global environmental objects.  For this type of API, side-by-side versions don't even make sense, as there can be only one environment.  And the root-level application project is really the only component that knows what the runtime environment will be.

The `"*"` approach basically makes all these problems the application's responsibility.  It's workable, but it is annoying because sometimes it's not straightforward to find a compatible set of versions.

That said, I share your feeling that "there must be a better way."  I just don't know what it would be. :-)

**Comment by nickpape-msft** [comment] 2018-07-24 19:59
@elliottsj I'm going to close this issue, although I mentioned it to Zoltan in another issue we have with PNPM that describes a similar class of issues.

**Closed by nickpape-msft** 2018-07-24 19:59 UTC
