### ISSUE TITLE
[api-extractor] Support "export { x }" for converting a source file's exports into a named module

### ISSUE THREAD

**Issue by donahut** [Microsoft/web-build-tools#663] opened 2018-05-19 16:58 UTC
Given an `index.ts` such as:
```
import * as d from './d';

export * from './A';
export * from './B';
export * from './C';

export {
    d
};
```

The generated `.apt.ts` only produces valid output for `A`, `B` and `C`, whereas `d` produces things like:
`// WARNING: The name ""<path>/lib/dts/d/index"" contains unsupported characters; API names should use only letters, numbers, and underscores`
and
`module "<path>/lib/dts/d/index" {`

This sort of local namespacing and export pattern is used throughout our codebase, so any workarounds would be welcome.

**Comment by pgonzal** [comment] 2018-05-28 04:32
This should get fixed during June as part of our sprint to convert the *.api.ts files to be generated using the new analysis engine that was created for the *.d.ts rollups.

**Comment by adventure-yunfei** [comment] 2018-08-14 03:58
@pgonzal  is this sovled now? still get this error.

**Comment by southpolesteve** [comment] 2018-11-01 14:22
I ran into this issue too. Was able to work around a by refactoring some of our exported types.

**Comment by pgonzal** [comment] 2018-11-22 07:34
The fix for this is related to Issue https://github.com/Microsoft/web-build-tools/issues/949 .  We'll tackle them together after AE7 is released.

**Comment by pgonzal** [comment] 2018-11-26 06:34
> I thought this issue is fixed by https://github.com/Microsoft/web-build-tools/pull/773, still not working? I'm using this syntax and it works fine for me. (tested with lastest version - api-extractor@6.1.6 and api-documenter@1.5.56)

@adventure-yunfei are you using .d.ts rollups?  Or just generating API documentation?  That might be the difference.

> This sort of local namespacing and export pattern is used throughout our codebase, so any workarounds would be welcome.

@donahut BTW the workaround is pretty easy.  For example, instead of this:

**d.ts**
```ts
  /**
    * (Doc comment for Example) 
    * @public 
    */
export class Example { }
```

**index.ts**
```ts
import * as d from './d';

// (doc comment won't be recognized here)
export { d };
```

...you could replace it with this:

**d.ts**
```ts
/**
  * (Doc comment for d) 
  * @public 
  */
export namespace d {
  /**
    * (Doc comment for Example) 
    * @public 
    */
  export class Example { }
}
```

**index.ts**
```ts
export { d } from './d';
```

**Comment by adventure-yunfei** [comment] 2018-11-26 14:57
> > I thought this issue is fixed by #773, still not working? I'm using this syntax and it works fine for me. (tested with lastest version - api-extractor@6.1.6 and api-documenter@1.5.56)
> 
> @adventure-yunfei are you using .d.ts rollups? Or just generating API documentation? That might be the difference.

Reproduced by myself. As you described, when enable "dtsRollup", it's not working... Seems I didn't consider this case.

**Comment by pgonzal** [comment] 2018-11-26 23:15
In API Extractor 7 all the features (docs, API reviews, and .d.ts rollups) will use the same analysis engine.  So we really need to prioritize this fix.

**Comment by adventure-yunfei** [comment] 2018-11-30 02:36
Tested with AE7, this case is entirely not supported (as the AE6 standalone documentation generator is gone), which becomes a block issue for my project.

I've tried to investigate. There're two slightly difference cases that are not supported now:

- case 1: import * from external package/module:
```typescript
import * as semver from 'semver';
export { semver };
```
- case 2: import * from local module:
```typescript
import * as local from './local';
export { local };
```

For **case 1**, the error is `Error: Child declaration not found for the specified node`, because the AstSymbol (returned from [SymbolAnalyzer. followAliases](https://github.com/Microsoft/web-build-tools/blob/d5e4425265383383007a3bdc7430b764893ba248/apps/api-extractor/src/analyzer/SymbolAnalyzer.ts#L84)) is ts SourceFileObject and thus set as "nominal" (in [AstSymbolTable._fetchAstSymbol](https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/analyzer/AstSymbolTable.ts#L300)), and then we skip it in [AstSymbolTable.analyze](https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/analyzer/AstSymbolTable.ts#L118). So declarations inside that SourceFileNode is not analyzed.

For **case 2**, the error is `Error: Unsupported export: blah...`, because in `SymbolAnalyzer.followAliases`, the symbol is falsely checked as `isAmbient` (see code [SymbolAnalyzer.ts#L142](https://github.com/Microsoft/web-build-tools/blob/d5e4425265383383007a3bdc7430b764893ba248/apps/api-extractor/src/analyzer/SymbolAnalyzer.ts#L142), the node is exactly kind of `ts.SyntaxKind.SourceFile`, but when searching we skip this start node).

Another possible problem of **case 2** is that in [SymbolAnalyzer. _followAliasesForImportDeclaration](https://github.com/Microsoft/web-build-tools/blob/d5e4425265383383007a3bdc7430b764893ba248/apps/api-extractor/src/analyzer/SymbolAnalyzer.ts#L292), inside the [_getPackagePathFromModuleSpecifier](https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/analyzer/SymbolAnalyzer.ts#L324) check we skip the local module import. I tried to make this check pass and return the absolutely local module path, but then the case falls back to the error of case 1.

From the code I see that the ts SourceFileObject type is currently treated as a special case. Seems a tough case for me to solve. Perhaps I need more time to study the new .d.ts rollup engine.

Could you please let me know whether someone is fixing this? If so, I'll wait for your good news and keep using AE6 (with my own fix) for now. If not, I may spend more time later to solve this blocking (for us) issue.

**Comment by pgonzal** [comment] 2018-11-30 02:44
I would love to get some community help with fixing various edge cases for the AE7 beta.

However, I feel like this particular issue may be difficult for an external contributor to fix, since it requires a design change for the **SymbolAnalyzer**.  I was planning to fix this myself, but first I need to work through a small punch list of other issues that are blocking our own projects from adopting AE7 (which is basically our bar for the first non-beta release of AE7).

If you're completely unable to continue testing AE7 without this fix, let me know and I can try to prioritize it sooner.

**Comment by adventure-yunfei** [comment] 2018-11-30 03:07
Thanks for quick response. Generally this issue won't actually affect my project, since I can continue to use AE6 (and yes if switching to AE7, this is a blocking issue for me). So it's fine to continue your plan for the first AE7 release.

The current situation is, with my own fix for AE6 (including the closed https://github.com/Microsoft/web-build-tools/pull/964), I can successfully generate an api document site which at least contains all exported items. The next feature I'm trying to do is enhance the type value link (e.g. the link for `IAadHttpClientConfigurations` of property `configurations`  from document https://docs.microsoft.com/en-us/javascript/api/sp-http/aadhttpclient?view=sp-typescript-latest#configurations , or the type link for `type` alias declaration). Before AE7 I actually didn't take much attention to the .d.ts rollup engine (as api document is our first mission). So I may first take time to see what's changing now.

By the way, I'm coming from a company and heavily take advantages of typescript (to build many 3D graphics related web apps). Cause of complex business logic, we indeed used some advanded features (or almost every possible one) of typescript. Since the code is huge now, we need such typescript related infrustructures. This project means too much for us! We're happy to take some time (but may be not much) to make some contribution to the growing typescript/tsdoc ecosystem!

**Comment by pgonzal** [comment] 2019-01-17 00:49
The following declaration types are now supported after PR #1002 was merged:

-  `"export { x }"`, including exporting the same symbol twice with two different names
- `import * as someName from 'external-package';`

This declaration type is still not implemented yet:
- `import * as someName from './localFile';`

I've opened a separate issue #1029 to track that.  Thus I am closing this issue.

**Closed by pgonzal** 2019-01-17 00:49 UTC
Labels: blocked, bug, effort: medium
