### ISSUE TITLE
@microsoft/load-themed-styles 1.7.82 fails build

### ISSUE THREAD

**Issue by PabloZaiden** [Microsoft/web-build-tools#796] opened 2018-08-29 13:33 UTC
The npm published package is broken again. This is the same that happened last week with #782

**Comment by gbellmann** [comment] 2018-08-29 19:41
@pgonzal fixed it last time, maybe he can help again.

**Comment by pgonzal** [comment] 2018-08-29 20:06
The `@microsoft/load-themed-styles` tarball seems to be okay:

https://unpkg.com/@microsoft/load-themed-styles@1.7.82/lib/index.js

Can you post a build log or other info indicating what's not building?

@iclanton

**Comment by iclanton** [comment] 2018-08-29 20:40
`1.7.83` has been published, which downgrades the upgraded tool that we believe caused a regression.

**Comment by iclanton** [comment] 2018-08-30 17:44
Closing this issue because we believe the underlying cause has been fixed. If you find that it hasn't, please reopen.

**Closed by iclanton** 2018-08-30 17:44 UTC
