### ISSUE TITLE
[rush] "rushx" compatibility with create-react-app (react-scripts) project?

### ISSUE THREAD

**Issue by hh83917** [Microsoft/web-build-tools#1059] opened 2019-01-31 07:35 UTC
We have a project started with create-react-app, we run rush update, cd to the folder and run "rushx start" (original script is yarn start) and get the following:
`sh: react-scripts: command not found`

I've check and react-scripts is in the node_modules folder and also listed in the rush update generated yaml file.

Is there a proper way or workarounds to use Rush with create-react-app projects without ejecting?

**Comment by octogonz** [comment] 2019-02-11 11:15
Is this a duplicate of Issue https://github.com/Microsoft/web-build-tools/issues/706?

**Comment by hh83917** [comment] 2019-02-11 11:44
@octogonz  Thanks for the reply. Yes, I guess it's a duplicate.
We are currently running with  `./node_modules/xxxpackage/.bin/` in package.json, but seems like a clunky solution. Glad to see this issue is going to be prioritized.

**Comment by octogonz** [comment] 2019-02-11 11:52
Okay I'll close this issue and bump the other one.

**Closed by octogonz** 2019-02-11 11:52 UTC
Labels: needs more info
